### PR TITLE
Upgrade gradle versions in the project.  Fix androidx dependencies.

### PR DESCRIPTION
**Pull request by IgorGanapolsky**
Upgrade to all latest gradle versions.  Fix androidx dependencies in code, as well as material design lib.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [X ] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Review by Alton09 — CHANGES_REQUESTED** [review]
Thanks for the contribution @IgorGanapolsky ! One thing so far. We can't yet use 7.x of the android gradle plugin as it is still in alpha, also it is currently failing to build because Java 11 is required with this version. Let's try to use the latest stable version `4.1.3` for now.

**Comment by IgorGanapolsky** [comment]
@Alton09  Changed gradle plugin to **4.1.3**

**Review by Alton09 — CHANGES_REQUESTED** [review]
Thanks @IgorGanapolsky! The pipeline is looking better. However, many of the other gradle modules are failing to build, for example the `exampleCustomAudioDevice`. I can help resolve these issues and get this PR ready to merge when I have some extra time if needed.

**Comment by IgorGanapolsky** [comment]
Ok, I went ahead and fixed the rest of **androidx** migration errors.
However, my local build fails Lint with this error:
> 
  /Users/igorganapolsky/.gradle/daemon/6.8.2/com/koushikdutta/async/AsyncSSLSocketWrapper$1.class: Error: checkClientTrusted is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers [TrustAllX509TrustManager]
  
Do you know what's happening there?

**Comment by Alton09** [comment]
@IgorGanapolsky Yeah so it looks like they added a new check in the linter in AGP `4.1.3` that is checking for an empty implementation of the `checkClientTrusted` method in the ion library that we are using to make simple HTTP requests. For now, we can add this lint error to the `baseline.txt` to ignore it. I'll be sure to add it to our todo list as a separate PR to swap out ion with something more widely used and secure like retrofit.

**Comment by IgorGanapolsky** [comment]
So just to confirm.  Do you want me to continue fixing this PR?

**Comment by Alton09** [comment]
@IgorGanapolsky Sorry for the late response on this one. The only thing left to do for this PR is to either ignore the lint error mentioned above or swap out ion with retrofit. I spent a few min trying to ignore the error and I wasn't able to find a quick way to suppress it. Feel free to add this last change, otherwise I'll work on adding in retrofit when I have some free time. Thanks!

**Comment by Alton09** [comment]
This work will be merged in via #664 . Thanks for your help on this one @IgorGanapolsky !

**Pull request closed without merging**
